# Generated by Django 3.0.11 on 2020-11-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20201111_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdiscount',
            options={'verbose_name': 'Order Discount', 'verbose_name_plural': 'Order Discounts'},
        ),
        migrations.AlterModelOptions(
            name='ordernote',
            options={'verbose_name': 'Order Note', 'verbose_name_plural': 'Order Notes'},
        ),
        migrations.AddField(
            model_name='line',
            name='est_dispatch_date',
            field=models.DateField(blank=True, null=True, verbose_name='Estimated Dispatch Date'),
        ),
        migrations.AddField(
            model_name='line',
            name='unit_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit Cost Price'),
        ),
        migrations.AddField(
            model_name='line',
            name='unit_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit Retail Price'),
        ),
    ]
